### ISSUE TITLE
bug in monte_carlo example

### ISSUE THREAD

**Issue by alex-romenskyi** [slawlor/ractor#162] opened 2023-09-11 12:49 UTC
**Describe the bug**
Monte_carlo example gives me an error like this:

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.22s
     Running `target/debug/examples/monte_carlo`
thread 'tokio-runtime-worker' panicked at 'Failed to send message: Messaging(SendErr)', ractor/examples/monte_carlo.rs:105:14
thread 'tokio-runtime-worker' panicked at 'Failed to send message: Messaging(SendErr)', ractor/examples/monte_carlo.rs:105:14
thread 'thread 'tokio-runtime-workertokio-runtime-worker' panicked at '' panicked at 'Failed to send message: Messaging(SendErr)Failed to send message: Messaging(SendErr)', ', ractor/examples/monte_carlo.rsractor/examples/monte_carlo.rs::105105::1414
```

Seems like when child actor ends itself, parent actor ends as well, but there are still several child actors who tries to send messages to their parent

**To Reproduce**
1. just downloaded repo and started with 

alexromensky@Alexs-MacBook-Pro ractor % cargo run --example monte_carlo

**Expected behavior**
supposed to run without an error

**Additional context**
MacOS 13.5.2, rustc 1.72.0 (5680fa18f 2023-08-23)

**Comment by nolmelab** [comment] 2023-09-11 23:36
I had the exactly same problem on Windows 10 / Intel i5-9500 6 core machine.
Some more facts are: 
- If NUM_GAMES is decreased to around 10, the problem does not happen. 
- If myself.stop() is disabled in Game::handle(), then the problem does not happen. 

I suspect that there are some race condition problem somewhere.

**Comment by nolmelab** [comment] 2023-09-12 03:48
When monte carlo is run in debug mode, the JoinHandle for GameManager actor immediately finishes. 

![image](https://github.com/slawlor/ractor/assets/133831637/6698ac0b-e91a-49a3-84f0-8ffb18a8390e)

This seems to be the cause of closed unbounded channels.

**Comment by slawlor** [comment] 2023-09-12 07:18
Thanks for reporting, it is a small edit which is described in #163. Should be fixed once merged.

**Closed** 2023-09-12 08:55 UTC
Labels: bug
