### ISSUE TITLE
How to communicate between local actors and remote actors across hosts using ractor? 

### ISSUE THREAD

**Issue by phil-skillwon** [slawlor/ractor#138] opened 2023-08-16 07:21 UTC
Hello, I'm very interested in ractor and am keen to use it in my project. I've previously used C++ CAF, which is also an open-source actor framework inspired by Erlang's actor model. I've noticed many similarities between ractor and CAF, which allows me to get started with ractor more quickly. However, I couldn't find any examples regarding communication between local and remote actors. Could you provide me with some examples of how to communicate with remote actors in ractor and ractor_cluster? For instance: an actor on Host A communicating with an actor on Host B, where the actor on Host B is considered a remote actor from the perspective of Host A.

**Comment by slawlor** [comment] 2023-08-16 11:13
Duplicate of discussion of same name and topic

**Closed** 2023-08-16 11:13 UTC
Labels: enhancement
